version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    main: ./main.go
    binary: bckt-mcp
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'

brews:
  - name: bckt-mcp
    homepage: https://github.com/vrypan/bckt-mcp
    description: "MCP server for formatting blog posts"
    license: MIT
    repository:
      owner: vrypan
      name: homebrew-bckt-mcp
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    directory: Formula
    install: |
      bin.install "bckt-mcp"
    test: |
      system "#{bin}/bckt-mcp", "--version"

release:
  github:
    owner: vrypan
    name: bckt-mcp
  draft: false
  prerelease: auto
